//! duoclip-proto: the DuoClip peer-to-peer control protocol.
//!
//! Small JSON messages exchanged between DuoClip apps over the authenticated WebRTC data
//! channel (and, as a fallback, relayed by the Worker). Every message is strictly validated
//! on both the encode and the decode path, and nothing in this crate panics on untrusted
//! input: all failures surface as [`ProtoError`].
//!
//! # Conventions (shared by all DuoClip crates)
//!
//! - Time is `i64` nanoseconds.
//!   - `*_utc_ns`: UTC, POSIX nanoseconds (leap seconds not counted), from the app's global
//!     clock.
//!   - `*_local_ns`: the sender's own monotonic clock (QPC-derived on Windows). Only
//!     meaningful to the sender, except in the time ping/pong exchange.
//! - IDs are UUIDs (v4 when generated by the apps; the version is not enforced on receipt).
//!   On the wire only the canonical lowercase hyphenated form is accepted, the same one used in
//!   object keys and AADs, so an id has exactly one textual spelling.
//! - Intervals are half-open, `[from, to)`, and `from < to` must hold.
//! - Nanosecond timestamps exceed 2^53, so a JSON consumer written in JavaScript cannot read
//!   them losslessly; the Worker must treat these messages as opaque.
//!
//! # Wire format
//!
//! `encode` produces the JSON of an [`Envelope`] (`{"v":1,"msg":{"type":"...",...}}`);
//! `decode` enforces [`MAX_MESSAGE_BYTES`], parses, checks the version, and validates.
//!
//! # Example
//!
//! ```
//! use duoclip_proto::{decode, encode, ClipId, ClipRequest, DeviceId, Message};
//!
//! let req = ClipRequest::with_defaults(
//!     ClipId::new_random(),
//!     DeviceId::new_random(),
//!     1_700_000_000_000_000_000, // hotkey press, global UTC ns
//!     5_000_000,                 // current clock uncertainty, ns
//! );
//! let bytes = encode(&Message::ClipRequest(req.clone()))?;
//! assert_eq!(decode(&bytes)?, Message::ClipRequest(req));
//! # Ok::<(), duoclip_proto::ProtoError>(())
//! ```
//!
//! # Object keys
//!
//! [`object_key`], [`manifest_key`] and [`clip_prefix`] define the one canonical layout of
//! encrypted clip objects in the bucket. A received [`ChunkRef`] is only structurally checked
//! by `validate`; receivers must also call [`ChunkRef::verify_object_key`] with their own crew
//! id so the announced key really belongs to the announced clip, POV, quality and index.

#![forbid(unsafe_code)]

mod codec;
mod error;
mod keys;
mod message;
mod types;

pub use codec::{decode, encode, Envelope};
pub use error::ProtoError;
pub use keys::{
    clip_prefix, manifest_key, object_key, validate_object_key, MAX_OBJECT_KEY_BYTES,
    OBJECT_KEY_PREFIX,
};
pub use message::{
    AckStage, ChunkRef, ClipAck, ClipRequest, Message, RejectReason, DEFAULT_MARGIN_POST_MS,
    DEFAULT_MARGIN_PRE_MS, DEFAULT_MAX_LEN_MS, DEFAULT_POST_MS, DEFAULT_PRE_MS,
    MAX_ACK_COVERAGE_INTERVALS, MAX_APP_VERSION_CHARS, MAX_CHUNK_BYTES, MAX_MARGIN_MS,
    MAX_OTHER_REASON_CHARS, MAX_POST_MS, MAX_PRE_MS, MAX_REQUEST_LEN_MS,
};
pub use types::{ClipId, CrewId, DeviceId, Interval, Quality, MAX_INTERVAL_NS};

/// Version of the control protocol spoken by this crate. Messages carrying any other version
/// are rejected by [`decode`] with [`ProtoError::UnsupportedVersion`].
pub const PROTOCOL_VERSION: u16 = 1;

/// Maximum size, in bytes, of one encoded message (envelope included).
pub const MAX_MESSAGE_BYTES: usize = 64 * 1024;
